export const PLANS = {
  one_month: {
    label: "One Time",
    price: 980,
    unit: "month",
    desc: "必要なタイミングで単発支援",
    borderColor: "border-slate-200",
    bgColor: "from-lime-400 to-emerald-500",
    hoverBgColor: "hover:from-lime-500 hover:to-emerald-600",
    textColor: "text-emerald-600",
    iconBg: "bg-emerald-500",
  },
  sub_monthly: {
    label: "Monthly",
    price: 680,
    unit: "month",
    desc: "毎月の継続サポート",
    borderColor: "border-slate-200",
    bgColor: "from-sky-500 to-cyan-500",
    hoverBgColor: "hover:from-sky-600 hover:to-cyan-600",
    textColor: "text-sky-600",
    iconBg: "bg-sky-500",
  },
  sub_yearly: {
    label: "Yearly",
    price: 6800,
    unit: "year",
    desc: "一番お得な年額サポート",
    borderColor: "border-teal-200",
    bgColor: "from-teal-500 to-emerald-500",
    hoverBgColor: "hover:from-teal-600 hover:to-emerald-600",
    textColor: "text-teal-600",
    iconBg: "bg-teal-500",
  },
};
